apiVersion: v1
kind: ConfigMap
metadata:
  name: jumpstarter-controller
  namespace: {{ include "jumpstarter.namespace" . }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: jumpstarter-controller
    {{ if .Values.global.timestamp }}
    deployment.timestamp: {{ .Values.global.timestamp | quote }}
    {{ end }}
data:
  # backwards compatibility
  # TODO: remove in 0.7.0
  {{ if .Values.authenticationConfig }}
  authentication: {{- .Values.authenticationConfig | toYaml | indent 1 }}
  {{ end }}
  config: |
{{ .Values.config | toYaml | indent 4 }}
  router: |
    default:
      endpoint: {{ include "jumpstarter.grpc.routerEndpoint" . }}
