{{ if eq .Values.grpc.mode "route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    external-exposed: "true"
    shard: external
  annotations:
    haproxy.router.openshift.io/timeout: 2d
    haproxy.router.openshift.io/timeout-tunnel: 2d
  name: jumpstarter-controller-route
  namespace: {{ include "jumpstarter.namespace" . }}
spec:
  host: {{ include "jumpstarter.grpc.hostname" . }}
  port:
    targetPort: 8082
  tls:
    termination: {{ .Values.grpc.tls.mode }}
    insecureEdgeTerminationPolicy: None
    {{ if .Values.grpc.tls.controllerCertSecret }}
    externalCertificate:
      name: {{ .Values.grpc.tls.controllerCertSecret }}
    {{ end }}

  to:
    kind: Service
    name: jumpstarter-grpc
    weight: 100
  wildcardPolicy: None
{{ end }}
