apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: jumpstarter-controller
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: jumpstarter-grpc
  namespace: {{ include "jumpstarter.namespace" . }}
  {{- $annotations := include "jumpstarter.annotations" . }}
  {{- if $annotations }}
  annotations:
  {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.grpc.nodeport.enabled }}
  type: NodePort
  {{ end }}

  ports:
  - name: grpc
    port: 8082
    protocol: TCP
    targetPort: 8082
    appProtocol: h2c # HTTP/2 over cleartext for gRPC (fixes edge termination in ingress/router)
    {{ if .Values.grpc.nodeport.enabled }}
    nodePort: {{ .Values.grpc.nodeport.port }}
    {{ end }}
  selector:
    control-plane: controller-manager
