{{ if eq .Values.grpc.mode "route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    external-exposed: "true"
    shard: external
  annotations:
    haproxy.router.openshift.io/timeout: 2d
    haproxy.router.openshift.io/timeout-tunnel: 2d
  name: jumpstarter-router-route
  namespace: {{ include "jumpstarter.namespace" . }}
spec:
  host: {{ include "jumpstarter.grpc.routerHostname" . }}
  port:
    targetPort: 8083
  tls:
    {{ if eq .Values.grpc.tls.mode "passthrough" }}
    termination: passthrough
    {{ end }}
    {{ if eq .Values.grpc.tls.mode "reencrypt" }}
    termination: reencrypt
    {{ end }}
    insecureEdgeTerminationPolicy: None
    {{ if .Values.grpc.tls.routerCertSecret }}
    externalCertificate:
      name: {{ .Values.grpc.tls.routerCertSecret }}
    {{ end }}

  to:
    kind: Service
    name: jumpstarter-router-grpc
    weight: 100
  wildcardPolicy: None
{{ end }}
